export interface Applications {
    'id': number   ,
    'study_year': string,
    'father_full_name': string,
    'nationality': string,
    'father_national_id': string,
    'mobile': string,
    'email': string,
    'student_name': string,
    'gender': string,
    'student_national_id': string,
    'date_of_birth': string,
    'place_of_birth': string,
    'health_status': string,
    'study_type': string,
    'bus': string,
    'civil_status_book': string,
    'certificate_of_vaccination': string,
    'certificate_of_birth': string,
    'student_national_id_photo': string,
    'father_national_id_photo': string,
    'cost': number,
    'tax':  number,
    'total_cost':  number,
    'class_id':  number,
    'user_id':  number,
    'status': string,
    'exam_id':  number
}
